# Generated by Django 3.2.10 on 2021-12-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='about',
            field=models.CharField(default='Vacay', max_length=140),
        ),
    ]
